# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class Concept(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class Episode(BaseModel):
    name: typing.Optional[str] = None
    number: typing.Optional[int] = None
    description: typing.Optional[str] = None

class GraphExtraction(BaseModel):
    podcasts: typing.List["Podcast"]
    episodes: typing.List["Episode"]
    topics: typing.List["Topic"]
    concepts: typing.List["Concept"]
    technologies: typing.List["Technology"]
    people: typing.List["Person"]
    links: typing.List["ReferenceLink"]
    relationships: typing.List["Relationship"]

class Person(BaseModel):
    name: typing.Optional[str] = None
    role: typing.Optional[typing.Union[typing_extensions.Literal['Host'], typing_extensions.Literal['Guest'], typing_extensions.Literal['Referenced Expert']]] = None

class Podcast(BaseModel):
    title: typing.Optional[str] = None

class ReferenceLink(BaseModel):
    text: typing.Optional[str] = None
    url: typing.Optional[str] = None

class Relationship(BaseModel):
    source_node: typing.Optional[str] = None
    target_node: typing.Optional[str] = None
    relationship_type: typing.Optional[types.RelationshipType] = None

class Technology(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class Topic(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
