# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class RelationshipType(str, Enum):
    INTERVIEWED_BY = "INTERVIEWED_BY"
    LEARNING_FROM = "LEARNING_FROM"
    COVERS_CONCEPT = "COVERS_CONCEPT"
    COVERS_TECHNOLOGY = "COVERS_TECHNOLOGY"
    HAS_TOPIC = "HAS_TOPIC"
    HAS_REFERENCE_LINK = "HAS_REFERENCE_LINK"
    GUEST_ON = "GUEST_ON"
    HOSTS = "HOSTS"
    MENTIONED = "MENTIONED"
    LISTENS_TO = "LISTENS_TO"
    LISTENS_TO_EPISODE = "LISTENS_TO_EPISODE"
    SUBSCRIBES_TO = "SUBSCRIBES_TO"

# #########################################################################
# Generated classes (21)
# #########################################################################

class Approach(BaseModel):
    description: str
    methodology: typing.Optional[str] = None
    plan: "Plan"

class Concept(BaseModel):
    name: str
    description: typing.Optional[str] = None

class Episode(BaseModel):
    name: str
    number: int
    description: typing.Optional[str] = None

class GraphExtraction(BaseModel):
    podcasts: typing.List["Podcast"]
    episodes: typing.List["Episode"]
    topics: typing.List["Topic"]
    concepts: typing.List["Concept"]
    technologies: typing.List["Technology"]
    people: typing.List["Person"]
    links: typing.List["ReferenceLink"]
    relationships: typing.List["Relationship"]

class Methods(BaseModel):
    name: str
    description: str
    steps: typing.Optional[typing.List[str]] = None

class Outcomes(BaseModel):
    description: str
    successCriteria: typing.List[str] = Field(description='How would we know that the project succeeded?')
    measurableResults: typing.Optional[typing.List[str]] = Field(default=None, description='Post-implementation actual measured results that demonstrate this specific outcome was achieved (e.g., \'Pipeline processes 1000 records/day\', \'System handles 1200 requests/min\')')

class Person(BaseModel):
    name: str
    role: typing.Optional[typing.Union[typing_extensions.Literal['Host'], typing_extensions.Literal['Guest'], typing_extensions.Literal['Referenced Expert']]] = None

class Plan(BaseModel):
    name: str
    description: str
    methods: typing.List["Methods"]
    tools: typing.List["Tools"]
    timeline: typing.Optional[str] = None
    milestones: typing.Optional[typing.List[str]] = None

class Podcast(BaseModel):
    title: str

class Project(BaseModel):
    name: str = Field(description='What is the name of the project?')
    description: str = Field(description='What is the description of the project?')
    employer: str = Field(description='Employer of the project?')
    location: str = Field(description='Location of the project?')
    startDate: typing.Optional[str] = Field(default=None, description='Start date of the project?')
    endDate: typing.Optional[str] = Field(default=None, description='End date of the project?')
    duration: typing.Optional[str] = Field(default=None, description='Duration of the project?')
    purpose: "Purpose" = Field(description='Why are we doing this project?')
    value: "Value" = Field(description='What would the benefit to the organization be if the project succeeded?')
    outcomes: typing.List["Outcomes"] = Field(description='What will we accomplish? How would we know that the project succeeded?')
    technologies: typing.List["Technologies"] = Field(description='What technologies will we use?')
    approach: "Approach" = Field(description='How will we going  to do this project?')
    team: "Team" = Field(description='Who is going to do what on the project? What resources will we need to complete the project?')

class Purpose(BaseModel):
    description: str
    objectives: typing.List[str] = Field(description='What the project aims to accomplish in order to fullfill the purpose? It is concrete, measurable and breaks down purpose into actionable component')

class ReferenceLink(BaseModel):
    text: str
    url: str

class Relationship(BaseModel):
    source_node: str
    target_node: str
    relationship_type: RelationshipType

class Responsibilities(BaseModel):
    description: str
    tasks: typing.List[str]
    deliverables: typing.Optional[typing.List[str]] = Field(default=None, description='Concrete deliverables or outputs produced by fulfilling this responsibility')

class Roles(BaseModel):
    name: str
    description: str
    responsibilities: typing.List["Responsibilities"]

class Team(BaseModel):
    name: str
    description: typing.Optional[str] = None
    roles: typing.List["Roles"]
    members: typing.Optional[typing.List[str]] = None

class Technologies(BaseModel):
    name: str
    description: str

class Technology(BaseModel):
    name: str
    description: typing.Optional[str] = None

class Tools(BaseModel):
    name: str
    description: str
    category: typing.Optional[str] = None

class Topic(BaseModel):
    name: str
    description: typing.Optional[str] = None

class Value(BaseModel):
    description: str
    benefits: typing.List[str] = Field(description='Specific benefits the organization will receive if the project succeeds')
    metrics: typing.Optional[typing.List[str]] = Field(default=None, description='Organization-level metrics that quantify the value/benefit delivered to the organization (e.g., ROI, efficiency gains, cost savings, reduction in integration time)')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
