# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Concept": types.Concept,
    "stream_types.Concept": stream_types.Concept,

    "types.Episode": types.Episode,
    "stream_types.Episode": stream_types.Episode,

    "types.GraphExtraction": types.GraphExtraction,
    "stream_types.GraphExtraction": stream_types.GraphExtraction,

    "types.Person": types.Person,
    "stream_types.Person": stream_types.Person,

    "types.Podcast": types.Podcast,
    "stream_types.Podcast": stream_types.Podcast,

    "types.ReferenceLink": types.ReferenceLink,
    "stream_types.ReferenceLink": stream_types.ReferenceLink,

    "types.Relationship": types.Relationship,
    "stream_types.Relationship": stream_types.Relationship,

    "types.Technology": types.Technology,
    "stream_types.Technology": stream_types.Technology,

    "types.Topic": types.Topic,
    "stream_types.Topic": stream_types.Topic,


    "types.RelationshipType": types.RelationshipType,

}