# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class RelationshipType(str, Enum):
    INTERVIEWED_BY = "INTERVIEWED_BY"
    LEARNING_FROM = "LEARNING_FROM"
    COVERS_CONCEPT = "COVERS_CONCEPT"
    COVERS_TECHNOLOGY = "COVERS_TECHNOLOGY"
    HAS_TOPIC = "HAS_TOPIC"
    HAS_REFERENCE_LINK = "HAS_REFERENCE_LINK"
    GUEST_ON = "GUEST_ON"
    HOSTS = "HOSTS"
    MENTIONED = "MENTIONED"
    LISTENS_TO = "LISTENS_TO"
    LISTENS_TO_EPISODE = "LISTENS_TO_EPISODE"
    SUBSCRIBES_TO = "SUBSCRIBES_TO"

# #########################################################################
# Generated classes (9)
# #########################################################################

class Concept(BaseModel):
    name: str
    description: typing.Optional[str] = None

class Episode(BaseModel):
    name: str
    number: int
    description: typing.Optional[str] = None

class GraphExtraction(BaseModel):
    podcasts: typing.List["Podcast"]
    episodes: typing.List["Episode"]
    topics: typing.List["Topic"]
    concepts: typing.List["Concept"]
    technologies: typing.List["Technology"]
    people: typing.List["Person"]
    links: typing.List["ReferenceLink"]
    relationships: typing.List["Relationship"]

class Person(BaseModel):
    name: str
    role: typing.Optional[typing.Union[typing_extensions.Literal['Host'], typing_extensions.Literal['Guest'], typing_extensions.Literal['Referenced Expert']]] = None

class Podcast(BaseModel):
    title: str

class ReferenceLink(BaseModel):
    text: str
    url: str

class Relationship(BaseModel):
    source_node: str
    target_node: str
    relationship_type: RelationshipType

class Technology(BaseModel):
    name: str
    description: typing.Optional[str] = None

class Topic(BaseModel):
    name: str
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
