#!/usr/bin/env python3
"""
cleanup_legacy_projects.py

 Safely cleans up all legacy `Project` nodes and their structural children
 from the Neo4j database to prepare for the new Deterministic Graph Resume.
 
 WARNING: This will permanently delete all nodes with the labels listed below.
 It will NOT touch core CortexModel nodes like Podcast, Episode, Chunk, Person.
"""

import sys
from dotenv import load_dotenv
from typing import List
from neo4j import GraphDatabase
import os

# Load environment variables
load_dotenv('.env', override=True)

NEO4J_URI = os.getenv("NEO4J_URI", "neo4j://localhost:7687")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")

# The precise list of labels generated by the legacy project_extractor.py
LEGACY_PROJECT_LABELS = [
    'Project', 'Purpose', 'Objective', 'Value', 'Benefit', 'Metric',
    'Outcome', 'SuccessCriteria', 'MeasurableResult', 'Approach',
    'Plan', 'Method', 'MethodStep', 'Tool', 'Timeline', 'Milestone',
    'Team', 'Role', 'Responsibility', 'Task', 'Deliverable', 'TeamMember',
    'Company' # Including the new one just in case
]

def cleanup_legacy_projects():
    if not NEO4J_PASSWORD:
        print("Error: NEO4J_PASSWORD environment variable is not set.")
        sys.exit(1)

    print(f"Connecting to Neo4j at {NEO4J_URI}...")
    
    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))
    
    try:
        with driver.session() as session:
            print("\nWARNING: This will DETACH DELETE all nodes with the following labels:")
            print("\n".join([f"  - {label}" for label in LEGACY_PROJECT_LABELS]))
            
            confirm = input("\nAre you sure you want to proceed? (y/n): ")
            if confirm.lower() != 'y':
                print("Cleanup cancelled.")
                return

            print("\nExecuting cleanup...")
            
            # Neo4j doesn't allow dynamic labels in MATCH (n:X), so we iterate or use a combined query
            query = f"""
            MATCH (n)
            WHERE ANY(label in labels(n) WHERE label in $legacy_labels)
            WITH n LIMIT 10000
            DETACH DELETE n
            RETURN count(n) as deleted_count
            """
            
            # We loop the query until it returns 0 deleted to handle large graphs
            total_deleted = 0
            while True:
                result = session.run(query, legacy_labels=LEGACY_PROJECT_LABELS)
                record = result.single()
                deleted = record["deleted_count"] if record else 0
                total_deleted += deleted
                print(f"  Deleted {deleted} nodes in this batch...")
                if deleted == 0:
                    break
                    
            print(f"\nCleanup complete. Total legacy project nodes deleted: {total_deleted}")
            print("The database is now ready for the new Deterministic Graph Resume seed script.")
            
    except Exception as e:
        print(f"Error during cleanup: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        driver.close()

if __name__ == "__main__":
    cleanup_legacy_projects()
